#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <netdb.h>
#include <ctype.h>

void createUdpSocket();
void reg();
void unr();
void login();
void logout();
void gls();
void gsr();
void gur();
void glm();
void errorSendingMsg();
